### ISSUE TITLE
Init.pl is trapped by POSIX commands (Centos 8)

### ISSUE THREAD

**Issue by ifishlin** [inutano/cwl-metrics#12] opened 2020-11-09 22:01 UTC
Hi, I can't make the cwl-metrics runnable on Centos 8. The command <code> cwl-metrics start </code>always be stuck somewhere. I spend much time to find where the problem was. 
In the end, I figured out the <code> init.pl </code> was trapped by two POSIX commands, <code> POSIX::sysconf  </code> and <code> POSIX::close  </code>.

After several times of failure, the system will crash. (can't log in anymore)
My environment is a Centos 8 VM on OpenStack. Do you know how to solve it?

Thanks

By the way, I tried the cwl-metrics on macOS, and it works.

<code>
sub daemonize {

    ### first fork
    my $pid = fork();
    if ($pid < 0) {
        exit(-1)
    }
    if ($pid > 0) {
        exit(0);
    }
    chdir("/");
    POSIX::umask(0) || die "Failed to daemonize: POSIX::umask()\n";
    POSIX::setsid() || die "Failed to daemonize: POSIX::setsid()\n";

    ### second fork
    $pid = fork();
    if ($pid < 0) {
        exit(-1);
    }
    if ($pid > 0) {
        exit(0);
    }
    my $oldStderr = select(STDERR);
    $| = 1;
    select($oldStderr);
    my $oldStdout = select(STDOUT);
    $| = 1;
    select($oldStdout);
    $pid = $$;
    system("echo $pid > $pidFile");
    foreach (0 .. (POSIX::sysconf (&POSIX::_SC_OPEN_MAX) || 1024)) { # trapped  
        POSIX::close $_  # trapped 
    }
    open(STDIN, "</dev/null");
    open(STDOUT, ">/dev/null");
    open(STDERR, ">/dev/null");
}
</code>

**Comment by ifishlin** [comment] 2020-11-10 10:04
Hi, some updates. I tried it on Ubuntu 20.04, also on a VM of the OpenStack. It also was trapped in the same POSIX commands.
Could it possible caused by the OpenStack? a cloud environment? thanks
(I did set vm.max_map_count to 262144)

<pre>
Digest: sha256:236460d32ceec855dc750e5998be367090a291d5eb09ae13b8b89551140cc17e
Status: Downloaded newer image for quay.io/inutano/cwl-metrics-client:0.1.12.6
quay.io/inutano/cwl-metrics-client:0.1.12.6
CWL-metrics initialization complete. Starting system...
Starting CWL-metrics...
Creating Elasticsearch index... <== stuck here.
</pre>

**Comment by inutano** [comment] 2020-11-11 03:09
Hello @ifishlin, thanks for the report! I suspect the first one would come from the incompatibility of the Perl module to monitor the processes with the host OS. I am not sure but it could be because of the OpenStack since I usually use CWL-metrics on native Ubuntu and Amazon Linux.

The second one can be caused by the limitation of memory assigned to the Docker daemon, I recommend to assign at least more than 4GB. Can you check the total amount of memory assigned to Docker with `docker info`?

**Comment by ifishlin** [comment] 2020-11-11 22:01
@inutano Thanks for your reply. Here is the output of my "docker info." 
Do you have a solution to the first question? Is there any possibility not caused by OpenStack?

<pre>
yuyulin@benchmark-cwl:~$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 0
  Paused: 0
  Stopped: 5
 Images: 7
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-52-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 28
 Total Memory: 125.8GiB
 Name: benchmark-cwl
 ID: LJPX:XI4X:ITL4:7ADE:DC3U:E7K7:MTRJ:R6SL:B6JN:ILDN:O2CI:VOG5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://www-int2.dkfz-heidelberg.de:80
 HTTPS Proxy: http://www-int2.dkfz-heidelberg.de:80
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
</pre>

**Comment by ifishlin** [comment] 2020-11-11 22:35
@inutano Hi, I was wondering whether the problem is caused by using POSIX::close() to close an int ($_ in the foreach). I checked the perl document, and it indicates the parameter should be a file descriptor. I'm not good at perl. Could this be the source of the problem? 

https://perldoc.perl.org/POSIX
<pre>
close
Close the file. This uses file descriptors such as those obtained by calling POSIX::open.

$fd = POSIX::open( "foo", &POSIX::O_RDONLY );
POSIX::close( $fd );
Returns undef on failure.

See also "close" in perlfunc.
</pre>

The code in init.pl

<pre>
foreach (0 .. (POSIX::sysconf (&POSIX::_SC_OPEN_MAX) || 1024)) { 
    POSIX::close $_  <== the $_ is an int. command is trapped here.
}
</pre>

**Comment by inutano** [comment] 2020-11-12 03:33
The Perl daemon script is written by a guy who already left the team, and I'm not an expert of Perl as well, but I assume this is caused by the different behavior in the Perl program. I suspect he referenced this sof entry:
https://stackoverflow.com/questions/766397/how-can-i-run-a-perl-script-as-a-system-daemon-in-linux

POSIX::close seems to be able to handle the int argument as it works well in the other environment, which I confirmed with my macOS (Perl v5.18.4) and centos8 (Perl v5.26.3). It may be because of the Perl version or the different system configuration around the POSIX constant. What is your Perl version?

**Comment by ifishlin** [comment] 2020-11-12 22:32
My perl version is the same as yours, centos8 (Perl v5.26.3). Perhaps it's really caused by the OpenStack and I have no clue to fix it. So, I tried to rewrite the code about closing all the files. I tested the following code and it would not crashed my VM. 

<pre>
# close all filehandles
for (glob "/proc/$$/fd/*") { POSIX::close($1) if m{/(\d+)$}; }
</pre>

I will use the code upper to replace the code below and will let you whether it works.

<pre>
foreach (0 .. (POSIX::sysconf (&POSIX::_SC_OPEN_MAX) || 1024)) {
   POSIX::close $_
}
</pre>

But, I don't understand, why the daemon have to close all the fd before starting?

**Comment by inutano** [comment] 2020-11-13 13:58
Great that you found the way! An article said that the reason to close all the fd is to prevent outputs from the parent process show up on a newly created terminal.

I have a plan of version 2 of the CWL-metrics which deprecated this Perl daemon, I hope it will work with no error on an openstack environment.

I'm closing this issue but please feel free to ask me anything to help you!

**Closed as completed by inutano** 2020-11-13 13:58 UTC
